# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hammerstad
description:      'A graveyard for my thoughts'
url:              https://hammerstad.github.io
baseurl:          /

author:
  name:           'Eirik Mildestveit Hammerstad'
  url:            https://github.com/hammerstad

paginate:         5

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

# Tagging
tag_page_layout: tags_index
tag_page_dir: tag

disqus:
    shortname: hammerstad